<?php

/**
* Implements hook_block_info()
*/

function pld_featured_objects_block_info() {
	$blocks['pld_featured_objects'] = array(
		'info' => t('Prov Lib Digital Featured Objects')
	);

	return $blocks;
}


function pld_featured_objects_block_view($delta = '') {
	switch($delta) {
		case 'pld_featured_objects':
		if(user_access('access content')) {
			$block['subject'] = NULL;
			$block['content'] = pld_featured_objects_items();
			return $block;
		}
	}
} 

function pld_featured_objects_items() {
	$items = array();

	module_load_include('inc', 'islandora', 'includes/datastream');
  	module_load_include('inc', 'islandora', 'includes/utilities');
 	module_load_include('inc', 'islandora', 'includes/metadata');

 	$user = user_load(1);

 	$connection = islandora_get_tuque_connection($user);

 	$repository = $connection->repository;

 	$ri = $repository->ri;

 	$collections = array();
 	$objects = array();

 	$cmodel = 'islandora:collectionCModel';

 	$query = <<<EOQ
 	SELECT ?pid ?label
 	FROM <#ri>
 	WHERE {
 		?pid <fedora-model:label> ?label ;
 		<fedora-model:hasModel> <info:fedora/$cmodel>
 	}
EOQ;

 	$results = $ri->sparqlQuery($query);
 	foreach($results as $r) {
 		$pid = $r['pid']['value'];
 		$label = $r['label']['value'];
 		if($pid != 'islandora:root') {
 			$collections[] = array(
 				'pid' => $pid,
 			);
 		}
 	}

 	foreach($collections as $c) {

 		$pid = $c['pid'];
 		
 		$parent_object = islandora_object_load($pid);

 		//var_dump($parent_object);

 		$object_query = <<<EOQ
 			PREFIX fedora: <info:fedora/fedora-system:def/relations-external#>
 			SELECT ?pid ?label 
 			FROM <#ri>
 			WHERE {
 				?pid fedora:isMemberOfCollection <info:fedora/$pid> ;
 				<fedora-model:label> ?label ;
 			}
EOQ;

 		$object_results = $ri->sparqlQuery($object_query);

 		foreach($object_results as $obj) {
 			$obj_pid = $obj['pid']['value'];
 			$obj_label = $obj['label']['value'];
 			$view_url = '';		
 			$obj_data = islandora_object_load($obj_pid);
 			$copyright = $obj_data->getDatastream('COPYRIGHT-RESTRICTION');

 			if($copyright) {
 				continue;
 			} else {
	 			$parent = $obj_data->getParents();
	 			$parent_pid = $parent[0];
	 			$parent_object = islandora_object_load($parent_pid);
	 			$parent_label = $parent_object->label;
	 			$parent_url = '/islandora/object/'.$parent_pid;
	 			$obj_url = '/islandora/object/'.$obj_pid;
	 			$obj_models = $obj_data->relationships->get('info:fedora/fedora-system:def/model#', 'hasModel');
	 			$copyright = $obj_data->getDatastream('COPYRIGHT-RESTRICTION');
	 			
	 			$obj_models = $obj_models[0]['object']['value'];
	 			
	 			if($obj_models == 'islandora:sp_basic_image') {
	 				$obj_dsid = $obj_data->getDatastream('OBJ');
	 				if($obj_dsid != FALSE) {
	 					$view_url = '/islandora/object/'.$obj_pid.'/datastream/OBJ/view';
	 				}
	 			}

	 			if($obj_models == 'islandora:compoundCModel') {

	 				$parts = islandora_compound_object_get_parts($obj_pid);

	 				if($parts) {
	 					$first_child = $parts[0];
	 					$object = islandora_object_load($first_child);
	 					$obj_dsid = $object->getDatastream('OBJ');
	 					$copyright = $object->getDatastream('COPYRIGHT-RESTRICTION');
	 					if($obj_dsid != FALSE) {
	 						$view_url = '/islandora/object/'.$first_child.'/datastream/OBJ/view';
	 					}
	 				}	
	 			}

	 			$objects[] = array(
	 				'obj_pid' => $obj_pid,
	 				'obj_label' => $obj_label,
	 				'obj_url' => $obj_url,
	 				'parent_label' => $parent_label,
	 				'parent_pid' => $parent_pid,
	 				'parent_url' => $parent_url,
	 				'view_url' => $view_url,
	 			);
 			}			
 		}
 	}
 	$rand = array_rand($objects);

 	$items = $objects[$rand];

	return theme('pld_featured_objects_items', array('items' => $items));
}

function pld_featured_objects_theme() {
	$base = array(
		'path' => drupal_get_path('module', 'pld_featured_objects').'/theme',
	);
	return array(
		'pld_featured_objects_items' => $base + array(
			'template' => 'pld-featured-objects',
			'variables' => array( 'items' => NULL,),
		),
	);
}



?>